[build]
dockerfile_path = "Dockerfile"

[deploy]
start_command = "sh -c 'python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT'"
healthcheck_path = "/api/patients/"
healthcheck_timeout = 100
restart_policy_type = "ON_FAILURE"

[envs]
DATA_DIR = "/data"
